output_root: '../'
#pytorch_data_dir: '/datadrive/pytorch-data/'
pytorch_data_dir: '/shared/mvg_dcs/UG_22-23/finn/'
experiment_name: "cityscapes"
res: 320
batch_size: 8
num_workers: 24
# Previous deep learning model (see paper)
run_picie: False
# Conditional random field
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False

model_paths:
  - "/shared/mvg_dcs/UG_22-23/finn/checkpoints/cityscapes/reproduce_results/epoch=0-mIoU=0-v1.ckpt"
  #- "/jmain02/home/J2AD003/txk70/zxc40-txk70/finn/git/STEGO_v2/saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
