#!/bin/bash
#SBATCH --partition=dcs-gpu
#SBATCH --account=dcs-res

#SBATCH --nodes=1
#SBATCH --gpus-per-node=1
#SBATCH --cpus-per-gpu=10
#SBATCH --mem-per-gpu=34G
#SBATCH --time=7-00:00:00

#SBATCH --output=output/%j.log
#SBATCH --mail-type=TIME_LIMIT_90,BEGIN,FAIL,END
#SBATCH --mail-user=fwilliams2@sheffield.ac.uk

module unuse /usr/local/modulefiles/live/eb/all /usr/local/modulefiles/live/noeb
module use /usr/local/modulefiles/staging/eb-znver3/all/
module load CUDAcore/11.1.1 GCC/11.2.0
module load Anaconda3
source activate stego_env

python torch_test_script.py

